apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: project ID on GCP
  artifacts:
    - image: us.gcr.io/"project ID on GCP"/hcsintegrationtool
      context: hcsintegrationtool
      docker:
        dockerfile: dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
